name: CI

on:
  push:
#    branches: master
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
#    branches: master
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
      - '*.yml'
      - '*.md'
      - 'docs/**'
      - 'LICENSE'

jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        COMPILER: [clang, gcc]
        include:
          - COMPILER: gcc
            DEPLOY_APPIMAGE: true
    env:
#      CCACHE_DIR: /ccache
      BUILD_ARTIFACTSTAGINGDIRECTORY: /artifacts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker setup and build
        run: |
          sudo mkdir /artifacts
          docker pull --quiet rpcs3/rpcs3-travis-xenial:1.4
          docker run                                           \
            -v $(pwd):/rpcs3                                   \
            --env-file .ci/travis.env                          \
            -v $CCACHE_DIR:/root/.ccache                       \
            -v $BUILD_ARTIFACTSTAGINGDIRECTORY:/root/artifacts \
            rpcs3/rpcs3-travis-xenial:1.4                      \
            /rpcs3/.ci/build-linux.sh
      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: ${{ env.BUILD_ARTIFACTSTAGINGDIRECTORY }}

  Build_Windows:
    runs-on: windows-latest
    env:
      COMPILER: msvc
      QT_VER: 5.14.2
      QT_DATE: 202003291224
      QTDIR: C:\Qt\$(QT_VER)\msvc2017_64
      VULKAN_VER: 1.2.135.0
      VULKAN_SDK_SHA: 181b3353612c8b0fc5e1857b652d62140191ae42b98f2f0d532cf349cebfd8c6
      VULKAN_SDK: C:\VulkanSDK\$(VULKAN_VER)
      CACHE_DIR: ./cache
      POWERSHELL_TELEMETRY_OPTOUT: 1
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download and unpack dependencies
        run: .ci/setup-windows.sh
      - uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VER }}
      - name: Export variables
        run: |
          .ci/export-azure-vars.sh
          echo '::set-env name=QTDIR::$env:Qt5_Dir'
      - uses: microsoft/setup-msbuild@v1
      - name: Compile SPIRV-Tools
        shell: powershell
        run: msbuild /m /p:"Platform=x64;Configuration=Release" Vulkan\spirv-tools-build\spirv-tools-build.vcxproj
      - name: Compile RPCS3
        shell: powershell
        run: msbuild /m /p:"Platform=x64;Configuration=Release - LLVM" rpcs3.sln
      - name: Pack up build artifacts
        run: .ci/deploy-windows.sh
